# services lists the multiple different apps we want to run via docker
services:
  # name for the service
  # api:
  #   # location of the Dockerfile
  #   build: ./server
  #   # ports
  #   ports:
  #     - 3000:3000

  # name for second service
  client:
    # dockerfile can be in different directory
    build: ./client
    # runs on a different port from first app
    ports:
      - 1234:1234
  db:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "mydb"
  adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080
